name: bizkit
description: A new Flutter project.
# build:
#   target:
#     release:
#       tree_shaking_target:
#         mode: "release"
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running flutter pub upgrade --major-versions. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run flutter pub outdated.
dependencies:
  animate_do: any
  bottom_bar_matu: ^1.3.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.0
  alphabet_scroll_view: ^0.3.2
  permission_handler: ^11.1.0
  contacts_service: ^0.6.3
  dartz: ^0.10.1
  dio: ^5.4.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  connectivity_plus: ^2.3.8
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.2
  path: ^1.8.3
  pinput: ^3.0.1
  loading_indicator: ^3.1.1
  file_picker: ^6.1.1
  url_launcher: ^6.2.4
  go_router: ^12.1.3
  pdf: ^3.10.8
  pdf_render: ^1.4.6
  path_provider: ^2.1.2
  crop_your_image: ^1.0.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  flutter_image_compress: any
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  share_plus: ^7.2.2
  # image_cropper: ^5.0.1
  device_info_plus: ^9.1.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  photo_view: ^0.15.0
  fluttertoast: ^8.2.5
  get: ^4.6.6
  flutter_staggered_grid_view: ^0.7.0
  easy_date_timeline: ^1.1.3
  dropdown_button2: ^2.3.9
  # custom_sliding_segmented_control: ^1.8.3
  syncfusion_flutter_datepicker: ^26.2.7
  open_file: ^3.3.2
  web_socket_channel: ^3.0.1
  excel: ^4.0.2
  flutter_pdfview: ^1.3.2
  flutter_sound: ^9.6.0
  just_audio: ^0.9.40
  mobile_scanner: ^5.2.3
  table_calendar: ^3.1.2
  injectable: ^2.5.0
  get_it: ^8.0.1
  cached_network_image: ^3.4.0
  flip_card: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.8
  delete_un_used_assets: ^1.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
  # - all new items
    - asset/module/module_manager/
    - asset/module/bizcard/

  # -old images remove after new ui build
    - asset/images/
    - asset/images/NavPngs/
    - asset/images/bottom sheet/
    - asset/images/onboarding/
    - asset/images/showcase images/
    - asset/images/icon/
    - asset/images/task_onboard/
    - asset/images/task/
    - asset/dev/
    - asset/dev/QR_code_for_mobile_English_Wikipedia.svg.png
    - asset/images/attendence module/attendence onboarding/
    - asset/images/attendence module/home screen btns/
    - asset/images/attendence module/home screen dialogs/
    - asset/images/attendence module/home screen clocks/
    - asset/images/attendence module/attendence secetion/
    - asset/module/bizcard/
    
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Euclid
      fonts:
        - asset: asset/fonts/Euclid Circular B Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Medium.ttf
          # weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages