part of 'business_data_bloc.dart';

@freezed
class BusinessDataState with _$BusinessDataState {
  const factory BusinessDataState(
      {required bool isLoading,
      required bool hasError,
      required bool loadCompanyData,
      required bool isBusiness,
      required bool businessLoading,
      required bool businessAdded,
      required bool logoLoading,
      required bool logoAdded,
      required bool bankingLoading,
      required bool bankingAdded,
            required bool socialMediaLoading,
      required bool socialMediaDeleteLoading,
      BusinessDetails? businessData,
      int? bankDetailsCreateId,
      required List<SocialMediaHandle> socialMedias,
      required List<Accredition> accreditions,
      required List<BranchOffices> branchOffices,
      required BusinessDetails businessDetails,
      required BankDetails bankDetails,
      required List<Product> products,
      required List<Brochure> brochures,
      ImageModel? logo,
      LogoCard? logoCard,
      Card? currentCard,
      required bool gotCompanyData,
      required List<Company> companiesList,
      String? message}) = _Initial;

  factory BusinessDataState.initial() => BusinessDataState(
      businessDetails: BusinessDetails(),
      bankDetails: BankDetails(),
      products: [],
      isLoading: false,
      businessAdded: false,
      businessLoading: false,
      socialMediaDeleteLoading: false,
      socialMediaLoading: false,
      logoAdded: false,
      logoLoading: false,
      bankingAdded: false,
      bankingLoading: false,
      hasError: false,
      isBusiness: false,
      socialMedias: [],
      accreditions: [],
      branchOffices: [],
      brochures: [],
      gotCompanyData: false,
      loadCompanyData: false,
      companiesList: []);
}
