// part of 'card_second_bloc.dart';

// @freezed
// class CardSecondState with _$CardSecondState {
//   const factory CardSecondState({
//     required bool contactAddLoading,
//     required bool contactAddError,
//     required bool contactAdded,
//     required bool locationFetchLoading,
//     required bool locationfetchError,
//     required bool isLoading,
//     required bool isPageLoading,
//     required bool hasError,
//     required bool pickImageLoading,
//     required bool pickSelfieCardLoading,
//     required bool cardScanFinish,
//     required bool secondCardcreated,
//     required bool secondCardLoading,
//     required bool secondCardEventLoading,
//     required bool deleteSecondCardLoading,
//     required bool deleteSecondCardEventLoading,
//     required bool updated,
//     required bool imagePickError,
//     required bool pickImageFirst,
//     required bool selfieImagePickerror,
//     required bool seondCardRestored,
//     required bool secondCardDeleted,
//     String? message,
//     String? locationAdress,
//     // required List<ImageModel> scannedImagesSecondCardCreation,
//     // ScannedImageDatasModel? scannedImageDatasModel,
//     // required List<ImageModel> selfieImageModel,
//     // required CardSecondCreateRequestModel cardSecondCreateRequestModel,
//     // CardSecondResponseModel? cardSecondResponseModel,
//     // required List<SecondCardNew> secondCards,
//     // List<SecondCardNew>? deleteSecondCards,
//     // GetSecondCardModel? getSecondCardModel,
//     // SuccessResponseModel? successResponseModel,
//   }) = _Initial;

//   factory CardSecondState.initial() => const CardSecondState(
//         contactAdded: false,
//         contactAddError: false,
//         contactAddLoading: false,
//         locationFetchLoading: false,
//         locationfetchError: false,
//         isLoading: false,
//         imagePickError: false,
//         pickSelfieCardLoading: false,
//         selfieImagePickerror: false,
//         //selfieImageModel: [],
//         pickImageLoading: false,
//         pickImageFirst: false,
//         secondCardEventLoading: false,
//         secondCardcreated: false,
//         seondCardRestored: false,
//         deleteSecondCardEventLoading: false,
//         secondCardDeleted: false,
//         isPageLoading: false,
//         updated: false,
//         deleteSecondCardLoading: false,
//         secondCardLoading: false,
//         //cardSecondCreateRequestModel: CardSecondCreateRequestModel(),
//         hasError: false,
//         //secondCards: [],
//         cardScanFinish: false,
//         // scannedImagesSecondCardCreation: [],
//       );
// }
