// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBj-cIudlcLeAwOB_TFjL2e9Cqk22uPHAA',
//     appId: '1:142144748161:web:c2918d91b1892f41d12b80',
//     messagingSenderId: '142144748161',
//     projectId: 'bizkit-a2182',
//     authDomain: 'bizkit-a2182.firebaseapp.com',
//     storageBucket: 'bizkit-a2182.appspot.com',
//     measurementId: 'G-J8F25LXPYR',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAdDdIrcFlXNq491V1aIRG8ibD3GNirpck',
//     appId: '1:142144748161:android:67912704b8e4a250d12b80',
//     messagingSenderId: '142144748161',
//     projectId: 'bizkit-a2182',
//     storageBucket: 'bizkit-a2182.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDJAZdJDMuws9IspvzbMqLo1eELc7OP_Cw',
//     appId: '1:142144748161:ios:8ff50287cc708475d12b80',
//     messagingSenderId: '142144748161',
//     projectId: 'bizkit-a2182',
//     storageBucket: 'bizkit-a2182.appspot.com',
//     iosBundleId: 'com.example.bizkit',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDJAZdJDMuws9IspvzbMqLo1eELc7OP_Cw',
//     appId: '1:142144748161:ios:2630d3e32fd31c17d12b80',
//     messagingSenderId: '142144748161',
//     projectId: 'bizkit-a2182',
//     storageBucket: 'bizkit-a2182.appspot.com',
//     iosBundleId: 'com.example.bizkit.RunnerTests',
//   );
// }
